// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBM0ICCImZ1fya122eK0weZ6u9PxTT2NM',
    appId: '1:1080582802745:web:d0ce43ed96c981229bece8',
    messagingSenderId: '1080582802745',
    projectId: 'kaam-test',
    authDomain: 'kaam-test.firebaseapp.com',
    storageBucket: 'kaam-test.appspot.com',
    measurementId: 'G-62446SH798',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pV9JHVmXi4cG8piRgZsSXgzNKX5VeMk',
    appId: '1:1080582802745:android:fc9e895d7948682a9bece8',
    messagingSenderId: '1080582802745',
    projectId: 'kaam-test',
    storageBucket: 'kaam-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLXChLoxnth0JO_T6FbMqVNI2Uq6kKn_U',
    appId: '1:1080582802745:ios:94b36e06b1b27e469bece8',
    messagingSenderId: '1080582802745',
    projectId: 'kaam-test',
    storageBucket: 'kaam-test.appspot.com',
    iosBundleId: 'com.example.kaamTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLXChLoxnth0JO_T6FbMqVNI2Uq6kKn_U',
    appId: '1:1080582802745:ios:94b36e06b1b27e469bece8',
    messagingSenderId: '1080582802745',
    projectId: 'kaam-test',
    storageBucket: 'kaam-test.appspot.com',
    iosBundleId: 'com.example.kaamTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBM0ICCImZ1fya122eK0weZ6u9PxTT2NM',
    appId: '1:1080582802745:web:eb38bad43ca0bfb69bece8',
    messagingSenderId: '1080582802745',
    projectId: 'kaam-test',
    authDomain: 'kaam-test.firebaseapp.com',
    storageBucket: 'kaam-test.appspot.com',
    measurementId: 'G-KPEK25ZH9G',
  );
}
